version: '3'

services:
  web:
    build: backend/.
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://docker:docker@pgdb:5432/task-er
    volumes:
      - ./backend:/usr/src/app
  pgdb:
    build: database/.
    ports:
      - "5432:5432"
